doc/address.md

I thought that providing a bit of a format for documenting the high level API 'verticals' would be a good way to align on deliverables. If we can start making these documents ahead of time they will provide a means to write tests / derive github issues and shape the library as we go.

Example doc format

---

.gitignore
bindings/py_wrappers/mini_shell.py
bindings/py_wrappers/pytest/address_test.py
bindings/py_wrappers/pytest/block_test.py
bindings/py_wrappers/wrappers.py

First version of Python wrapper
- key generation
- address generation
unit tests still in progress

Creating first Python wrapper PR

---

.gitignore
test/address_tests.c

This PR contains improved organization of address tests and some extra checks on hd/child addresses

C improved tests

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/ci.yml

Cherry-picked from [dogecoin/master at deeabe943](https://github.com/dogecoin/dogecoin/commit/deeabe9438a55da6b062992d83866930de4c3290)

issue template updated to prevent spam in repository

---

include/dogecoin/address.h
include/dogecoin/byteswap.h
include/dogecoin/ctaes.h
include/dogecoin/hash.h
include/dogecoin/net.h
include/dogecoin/portable_endian.h
include/dogecoin/protocol.h
include/dogecoin/script.h
include/dogecoin/serialize.h
include/dogecoin/transaction.h
include/dogecoin/tx.h
src/aes.c

-fix up (remove extraneous and alphabetize) headers
-add missing copyright to aes.c

trivial: fix up headers

---

doc/bindings.md
wrappers/python/pytest/cython_tests.sh

fix bad path for python wrapper in docs

---

contrib/examples/example.c
src/address.c

This PR includes fixes for #74. Setting to draft until I confirm it fixes the issues in example.c

address: fix memleaks caused from excessive key lengths

---

doc/tools.md

Updated print_keys  output and derive_child_keys parameters and output

Fixed command and ouputs for HD

---

doc/transaction.md

doc: update transaction signing definitions

---

doc/address.md
doc/getting_started.md
doc/tools.md
include/dogecoin/bip39.h
include/dogecoin/libdogecoin.h
src/bip39.c
src/cli/such.c

bip39: updated mnemonic wrappers
such: updated parameters
libdogecoin: updated types and mnemonic wrappers

docs: added bip39 seedphrases and libunistring

---

.gitignore
CMakeLists.txt
Makefile.am
include/dogecoin/libdogecoin.h
include/dogecoin/qrengine.h
include/qr/png.h
include/qr/qr.h
src/png.c
src/qr.c
src/qrengine.c
test/bip39_tests.c
test/qr_tests.c
test/unittester.c

Know that likely msvc cmake stuff has to be resolved before this goes in

0.1.2 dev QR support

---

include/dogecoin/utils.h
src/utils.c
test/unittester.c
test/utils_tests.c

-adds dogecoin_network_enabled function to determine whether WITH_NET is defined

utils: add dogecoin_network_enabled function

---

.gitignore
CMakeLists.txt
Makefile.am
include/dogecoin/libdogecoin.h
include/dogecoin/qrengine.h
include/qr/jpeg.h
src/jpeg.c
src/qrengine.c
test/qr_tests.c

now writes jpegs too because moms and dads love jpeg

added jpeg qr functionality using a modified version of jpec

---

.gitignore
contrib/examples/example.c
doc/address.md
include/dogecoin/libdogecoin.h

-add base documentation for both derived hd address functions. 
-add examples for derived hd address functions.
-add example to .gitignore

docs: finalize derived hd address functions

---

CMakeLists.txt
Makefile.am
include/dogecoin/moon.h
src/moon.c
test/moon_tests.c
test/unittester.c

Add Moon Files

---

.gitignore
CMakeLists.txt
Makefile.am
configure.ac
include/dogecoin/byteswap.h
include/dogecoin/dogecoin.h
src/cli/such.c
test/unittester.c

removed src from libdogecoin-config.h includes
added install target to cmake for libdogecoin
updated install in cmake to align with autotools
added config directory with .empty
updated .gitignore

added libdogecoin-config.h to install

---

Makefile.am
configure.ac
include/dogecoin/bip39.h
src/bip39.c
test/address_tests.c
test/unittester.c

bip39: added flag and ITERATIONS
bip39: added flag and checks to get_root_seed
bip39: updated error statements and seed parameter
make: removed libunistring link symbol
test: added flag to address_test and unittester

config: added config flag for unistring

---

test/wallet_tests.c

-this is old, non applicable code which ended up breaking msvs build, in particular calls to dogecoin_wtx_get_available_credit which were writing to memory after the end of the heap buffer.

qa: omit p2wpkh section from test_wallet

---

CMakeLists.txt
Makefile.am
include/dogecoin/block.h
include/dogecoin/map.h
src/block.c
src/map.c
test/spv_tests.c

-adds new map and hash structs for easier memory management when working with uint256 types and integrate in deserialize_dogecoin_auxpow_block

map: add files and use in deserialize_dogecoin_auxpow_block

---

src/cli/spvnode.c

updated wallet files and usage

spvnode: added headers files

---

include/dogecoin/libdogecoin.h

Expose the p2pkh utility functions.

lib: expose p2pkh utility functions

---

include/dogecoin/libdogecoin.h

Remove this function exposed in #145

dogecoin_tx_out function in header

---

CMakeLists.txt
configure.ac
src/seal.c

cmake: enabled TEST_PASSWD by default
config: added default is yes to TEST_PASSWD

seal: added TEST_PASSWD to tpm functions

---

doc/tools.md
include/dogecoin/seal.h
src/seal.c

docs: added encrypted backup guidance to tools.md

seal: added encrypted store directory

---

src/tx.c
test/wallet_tests.c

tx: emulate tx_in witness_stack vector in tx deser

---

.github/workflows/ci.yml

Adds native windows build and code signing for windows and macos to ci.

ci: added sign jobs for windows and macos

---

include/dogecoin/libdogecoin.h
include/dogecoin/tool.h

Updated parameter in headers to `privkey_wif` for consistency with the body.

tool: updated pubkey_from_privatekey param

---

src/wallet.c

Restores a logic check removed in #223.

wallet: restore logic check
