dogecoinfoundation/libdogecoin

.github/workflows/ql.yml

there is no python code in the repository thus we fail codeql analysis. omitting temporarily until python qa testing framework and tooltest is eventually ported.

qa: omit python from codeql

---

src/address.c
test/address_tests.c
test/unittester.c

this fixes issue #17 with generateDerivedHDPubkey() within src/address.c wherein if passing a hd master key with testnet prefix it derives a mainnet p2pkh address.

qa: address_test

---

.gitignore
bindings/py_wrappers/mini_shell.py
bindings/py_wrappers/pytest/address_test.py
bindings/py_wrappers/wrappers.py
configure.ac
include/dogecoin/address.h
include/dogecoin/utils.h
src/address.c
src/utils.c
test/address_tests.c

This branch features 2 new functions in address.c:
verifyPrivPubKeypair(), which takes a keypair as input and returns a boolean whether the provided private and public key are both valid and associated with each other
verifyP2pkhAddress(), which takes a p2pkh address only as input and returns a boolean whether the simple p2pkh address is formatted correctly and checks whether the entropy is above a certain threshold (0.3% false negative rate currently)
verifyPrivPubKeypair() is much more reliable as it validates the low-level building blocks of the keypair. verifyP2pkhAddress() is only a surface level evaluation of whether a p2pkh address "looks right"... not to be treated as an official verification method but as more of a placeholder for when we decide the rules for valid dogecoin …

Verify address

---

test/address_tests.c

Unit tests failed on Mac M1.
By increasing the array size to 35 all tests pass.
Will take a look on the reason why it is failing on Mac.

Fixing unit_tests - Increase size of char array

---

.github/workflows/ci.yml

revert i686/x86_64-w64-mingw32 to run on bionic after libwine:i386 workaround broke.

ci: fix apt-get update step for i686-w64-mingw32

---

doc/tools.md
doc/transaction.md
include/dogecoin/libdogecoin.h
include/dogecoin/transaction.h
include/dogecoin/tx.h
src/cli/such.c
src/script.c
src/transaction.c
src/tx.c
test/transaction_tests.c
test/tx_tests.c
wrappers/golang/libdogecoin/libdogecoin.go
wrappers/golang/libdogecoin/transaction_test.go
wrappers/python/libdogecoin/libdogecoin.pyx
wrappers/python/pytest/transaction_test.py

-remove unnecessary function variables from dogecoin_tx_sign_input and dogecoin_tx_sighash.
-remove unused function dogecoin_decode_op_n.
-subtract 1 from sigdata length in dogecoin_hash in tx_tests.

tx: remove bloat from dogecoin_tx_sign_input

---

src/base58.c
src/cli/such.c
src/net.c
src/random.c
src/utils.c

-replace manually set mem zero for buf in dogecoin_b58check with dogecoin_mem_zero.
-silence incorrect GCC warning regarding GetProcAddress and add update_seed to dogecoin_random_bytes_internal when building for *-w64-mingw32.
-remove implicit declaration of fsync(fileno(file)) in dogecoin_file_commit since we cover all target architectures.
-wrap node_periodical_timer function in conditional for x86_64-w64-mingw32 to declare arg fd as long long int else int.
-fix segfault when editing transaction output and add bounds checks for amount and destination address in edit output menu in such.

trivial: fix remaining GCC warnings/errors

---

doc/address.md
doc/bindings.md
doc/getting_started.md
doc/transaction.md

Replaces all instances of `github.com/jaxlotl/go-libdogecoin-sandbox` with `github.com/jaxlotl/go-libdogecoin`

Fix all go get errors caused by rename

---

src/script.c
test/tx_tests.c

- Fixed an issue with `dogecoin_script_copy_without_op_codeseperator` when parsing OP_PUSHDATA4 (it was reading out of bounds). It was also ignoring a failure state when there is not enough data to push, which hid the fact that the test inputs were actually failing
- Added some more checks in `test_script_parse()` and fixed the `script_tests` inputs so they don't have a 0x prefix (causing an erroneous \x00 prefix during hex2bin) and also added an appropriate amount of data to push for the OP_PUSHDATA1, OP_PUSHDATA2, and OP_PUSHDATA4 tests

Fix for dogecoin_script_copy_without_op_codeseperator todo

---

include/dogecoin/base58.h
src/base58.c

- Fixed memory cleanup issue in dogecoin_base58_encode_check  (size of pointer vs size of buffer)
- Updated the parameter names for dogecoin_base58_encode_check's declaration to match its definition. 
I honestly think base58 needs a normalization/cleanup pass for better readability and consistency with the rest of the api, once some naming guidelines and such have been established

Fixed memory cleanup issue in dogecoin_base58_encode_check and updated its declaration

---

include/dogecoin/libdogecoin.h

-expose both getDerivedHDAddress and getDerviedHDAddressByPath in libdogecoin.h
-expose cstr and tx headers in order to access dogecoin_private_key_wif_to_script_hash, dogecoin_p2pkh_to_script_hash and dogecoin_script_hash_to_p2pkh

expose derived hd address and p2pkh scripthash conversion functions

---

.github/workflows/ci.yml
.github/workflows/ql.yml

-node.js 12 actions are deprecated therefore bump to 16 by increasing actions/checkout@v2 and actions/cache@v2 to v3

ci/codeql: bump node.js actions from 12 to 16

---

configure.ac
include/dogecoin/constants.h
include/dogecoin/tx.h
include/dogecoin/utils.h
include/dogecoin/wallet.h
src/cli/spvnode.c
src/tx.c
src/utils.c
src/wallet.c

This PR introduces introduces possibility to add multiple watch addresses during spvnode initialization:
```
./spvnode -c -a "address address address" -b -p scan
```
It also has beginnings of daemon process (-z || --daemon) on linux/unix and rudimentary utxo byte array for transit via wire among other semi useful functions for radio use.
Big change is in how we convert script pubkeys to p2pkh addresses which now properly ser/deser.
That said there are still a number of memory leaks that have prevented any additional commits from being included as they are under heavy development and caused issues during sync. (I've successfully synced and scraped multiple addresses using this commit so am going to "call it" so to speak while I work on including some of the back logged stuff.)

spvnode/wallet: support multiple watch addresses per init

---

CMakeLists.txt

These files contain a conflicting `main` method.
I was able to compile after adding both as exclusions.

Additional `secp256k1` Source Exclusions

---

CMakeLists.txt

-this commit allows building shared lib via cmake by passing the flag -DBUILD_SHARED_LIBS=1 during configuration (cmake -DBUILD_SHARED_LIBS=1 ../)

build: enable building shared lib via cmake

---

.github/workflows/ci.yml
contrib/scripts/sdk.sh

-bitcoin core updated their hosted version of Xcode-12.2-12B45b-extracted-SDK-with-libcxx-headers.tar.gz which broke our checksum validation. i wrote security@bitcoincore.org and received confirmation from fanquake that it was updated to reflect the checksum found here: https://github.com/bitcoin/bitcoin/tree/master/contrib/macdeploy#step-2-generating-xcode-122-12b45b-extracted-sdk-with-libcxx-headerstargz-from-xcodeapp

ci: update mac osx sdk checksum

---

wrappers/python/libdogecoin/setup.py

import libdogecoin false: 
ImportError: .....build/lib.linux-x86_64-3.9/libdogecoin.cpython-39-x86_64-linux-gnu.so: undefined symbol: uninorm_nfkd
fix it

bug-fix: python wrapper missing unistring

---

src/cli/spvnode.c
src/wallet.c

i'm going to make the previous pr more map centric and atomic. this one fixes issues found in successive starts to spvnode wiping out the wallet->waddr_rbtree and routes wtx's to proper vector on init.

wallet: fix rehydration of waddr_rbtree and route wtx to proper vector

---

src/wallet.c

-to account for user's accidentally (or purposely...) adding utxo's that total more than the amount of the output we need to iterate through the vin's and apply the same logic as we do with outputs with the caveat that that most likely means they are attempting to consolidate their utxo's into a single utxo for whatever reason.

wallet: make dogecoin_wallet_scrape_utxos account for edge case

---

src/spv.c
test/spv_tests.c

the following significantly expedites the time it's taking to run tests on ci. changes include:
-shorten the duration of downloading blocks near the tip
-switch spv_test back to testnet on account of resolution to testseed.jrn.me.uk

qa/spv: shorten block duration on ibd and switch to testnet for spv_test

---

depends/Makefile
depends/README.md
depends/hosts/android.mk
depends/packages/libevent.mk
doc/getting_started.md

This PR adds Android support (`aarch64-linux-android`) to the depends system through the Android SDK+NDK.

depends: Add support for Android

---

.github/workflows/ci.yml
include/dogecoin/utils.h
include/dogecoin/wallet.h
src/cli/spvnode.c
src/utils.c
src/wallet.c

-this PR fixes dogecoin_wallet_unregister_watch_address_with_node and allows multiple watch addresses to be removed at a time.
-testing can be achieved by dl the new main_wallet_jul1.db and main_headers_jun29.db and walking through the steps found here:
https://gist.github.com/xanimo/96f753bcc635dc30285ca72e3b6d3e44

wallet: fix dogecoin_wallet_unregister_watch_address_with_node

---

contrib/examples/example.c
include/dogecoin/libdogecoin.h

Exposes the tool functions to generate WIF keys and addresses and also updates the example.

0.1.3 dev expose tools

---

contrib/examples/example.c
include/dogecoin/libdogecoin.h

Exposes bip32, bip44 and private key encoding utilities.

Added bip and private key utilities

---

contrib/examples/example.c
doc/address.md
include/dogecoin/address.h
include/dogecoin/libdogecoin.h
src/address.c
test/address_tests.c

-attempting to provide a solution for language wrappers that need retrieving of the `dogecoin_hdnode`'s private key converted to WIF format, in addition to a similar function that allows retrieving the `dogecoin_hdnode` itself, while populating the out variable with the corresponding extended child key by path.

address: adds getHDNodeAndExtKeyByPath, getHDNodePrivateKeyWIFByPath

---

include/dogecoin/address.h
src/address.c
test/address_tests.c

The existing functions generated keys, not addresses. This code extracts common behavior to be shared between these functions and adds a function that return addresses (using the name of the previous function) and adds a new function name (using the body of the previous function) that returns HD public or private keys.
Addresses GH #152.
I generated addresses from the public keys through an entirely separate codebase to verify results.

Improve HD address derivation

---

contrib/examples/example.c
doc/address.md
include/dogecoin/bip32.h
include/dogecoin/bip39.h
include/dogecoin/bip44.h
include/dogecoin/chainparams.h
include/dogecoin/dogecoin.h
include/dogecoin/key.h
include/dogecoin/libdogecoin.h
include/dogecoin/tool.h
include/dogecoin/tx.h
include/dogecoin/vector.h
src/address.c
src/bip32.c
src/bip44.c
src/chainparams.c
src/cli/tool.c
src/key.c
src/tx.c
src/vector.c
src/wallet.c
test/bip32_tests.c
test/bip44_tests.c
test/key_tests.c
test/tool_tests.c
test/transaction_tests.c
test/vector_tests.c

address: added depth to dogecoin_hd_generate_key for extended keys
chainparams: added isTestnetFromB58Prefix and isMainnetFromB58Prefix wrappers
bip32: added wrappers and depth to dogecoin_hd_generate_key for extended keys
bip39: moved constant to header
bip44: added wrappers and updated to derive_bip44_extended_key
key: added wrappers
dogecoin: added key string and script constants
example: moved constants to header, updated for key string constants, indentation and to derive_bip44_extended_key
tool: added wrappers, assert for dogecoin_pubkey_get_hex call and depth to dogecoin_hd_generate_key for extended keys
tx: added wrapper
vector: added wrappers for serialization/deserialization
test: added wrappers to bip32, key, transaction, tool, and vector tests

lib: added key string constants, chainparams and bip32/44 wrappers

---

src/vector.c
test/address_tests.c
test/hash_tests.c
test/scrypt_tests.c
test/vector_tests.c

tests: added references and free to address_tests, hash_tests, scrypt_tests and vector_tests

vector: updated memory allocation in deserialize

---

doc/tools.md
include/dogecoin/utils.h
src/cli/spvnode.c
src/cli/such.c
src/seal.c
src/utils.c
src/wallet.c

Moved getpass from seal to utils for such and spvnode usage.

utils: added getpass

---

include/dogecoin/block.h
include/dogecoin/hash.h
include/dogecoin/wallet.h
src/auxpow.c
src/block.c
src/headersdb_file.c
src/spv.c
src/transaction.c
src/tx.c
src/wallet.c
test/address_tests.c
test/bip44_tests.c
test/block_tests.c
test/hash_tests.c
test/wallet_tests.c

Updates were made based on valgrind analysis results
`valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./tests`
`valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./spvnode -f 0 -y 0 -b -p scan`

hash: added dogecoin_hashwriter_free

---

include/dogecoin/wallet.h
src/wallet.c

-this pr removes 4 memleaks detected in `dogecoin_wallet_init` when passing in watch addresses. since we store the `waddr` in the `wallet->waddr_vector` we really just need to dispose of the `waddr` object being passed back during wallet init. this is also why `dogecoin_p2pkh_addr_from_hash160` was removed since it's unnecessary.

wallet: free waddrs in dogecoin_wallet_init

---

test/spv_tests.c

-expedite ci testing by lowering amount of headers synced to 32,000. this accounts for 16,000 non auxpow headers and 16,000 auxpow headers.

qa: lower amount of headers we sync in spv_tests

---

src/net.c
src/spv.c

Update to auto-reconnect on `Error connecting to node`, maintaining threshold.
```
DEBUG: Statecheck: amount of connected nodes: 4
DEBUG: received command from node 11: inv
DEBUG: received command from node 16: ping
DEBUG: sending message to node 16: pong
DEBUG: received command from node 16: inv
DEBUG: received command from node 25: inv
DEBUG: Get inv request with 14 items
DEBUG: Event callback on node 12
DEBUG: Error connecting to node 12.
DEBUG: Connected nodes: 3
DEBUG: Statecheck: amount of connected nodes: 3
```

net: updated check to connect nodes

---

doc/tools.md
include/dogecoin/headersdb.h
include/dogecoin/headersdb_file.h
include/dogecoin/spv.h
include/dogecoin/wallet.h
src/cli/spvnode.c
src/cli/such.c
src/headersdb_file.c
src/seal.c
src/spv.c
src/wallet.c
test/spv_tests.c
test/wallet_tests.c

Added prompts for wallet and header database files and moved `fcntl` to `dogecoin_spv_client_discover_peers` for delayed non-blocking stdin.

wallet: added prompt to dogecoin_wallet_load

---

.github/workflows/ci.yml
.gitignore
include/dogecoin/utils.h
include/dogecoin/wallet.h
rpctest/Dockerfile
rpctest/fetch.py
rpctest/path.sh
rpctest/spvtool.py
src/cli/spvnode.c
src/utils.c
src/wallet.c

-total redesign of dogecoin_unregister_watch_address_with_node to alleviate calls to concat
-populate wallet->filename on dogecoin_wallet_new otherwise it's populated by name and freed
-added replace_last_after_delim which searchs for a match and replaces with replacement
-added remove_substr which returns a string with substr removed
-changed wallet cmd to sanity
-sanity cmd test now iterates through multiple addresses
-free waddr and buf and call dogecoin_wallet_next_addr on edge case where we delete our last address
-refactor/fix spvtool.py, fetch.py, .gitignore dummy
-clear spvnode wallet sanity cmd of memleaks
-fix wallet sanity check on windows
-added file_copy function to utils
-check if file exists before performance of file operations
-free remaining waddr during sanity check …

wallet: clear memory leaks from radio doge functions

---

src/spv.c

This change removes the transmission of a reject message to a node when invalid or out-of-order blocks are received. A reject should not be sent in response to blocks that are valid but out of order.

spv: removed reject on invalid block

---

.github/workflows/ci.yml

This limits the sign actions added in #184 to tags and upgrades deprecated v3 actions to v4.

ci: added tag check to sign actions

---

CMakeLists.txt
src/cli/tool.c
src/eckey.c
src/key.c
src/seal.c
test/tpm_tests.c

Added `--config ${CMAKE_BUILD_TYPE}` to the `cmake --build` command to specify the build type for msvc.

cmake: added build type for msvc

---

src/headersdb_file.c
test/spv_tests.c

Update to `dogecoin_headers_db_connect_hdr` using `memcmp` to find common ancestor between forks and main chain for any depth of reorg and test.

headersdb_file: updated reorg to find common ancestor with memcmp

---

.github/workflows/ci.yml
src/logdb/test/logdb_tests.c
test/wallet_tests.c

This update completes #141 by adding an `aarch64-android` test to CI, installing SDK tools, running the emulator in a container and adding temp file paths in logdb and wallet tests for Android.

ci: added test for aarch64-android

---

src/bip39.c
src/seal.c

Added `fclose(fp)` to error conditions in `src/bip39.c` and `src/seal.c`.

bip39: added fclose to error conditions

---

include/dogecoin/spv.h
rpctest/spvtool.py
src/cli/spvnode.c
src/headersdb_file.c
src/net.c
src/spv.c
src/wallet.c
test/spv_tests.c

-constrain processing of inv messages to only those that are 500 or greater in length during ibd 
-only call getblocks when node->last_requested_inv is equal to pindex->hash 
-aggressively disconnect from peers who are non responsive longer than that of HEADERS_MAX_RESPONSE_TIME 
-change HEADERS_MAX_RESPONSE_TIME to 2 minutes which is reflective of parameters set in core 
-change BLOCKS_DELTA_IN_S to 60 (1 dogecoin mined per minute) which is proportionally representative of the original value of 600 or 10 minutes per bitcoin mined 
-compare chaintip->height with node->bestknownheight instead of chaintip->header.timestamp > client->oldest_item_of_interest - (BLOCK_GAP_TO_DEDUCT_TO_START_SCAN_FROM * BLOCKS_DELTA_IN_S) for calling sync_completed 
-conditionally call …

spv: optimize initial block download

---

.gitignore
contrib/examples/example.c
contrib/gitian-build.sh
contrib/gitian-descriptors/gitian-linux.yml
contrib/gitian-descriptors/gitian-osx.yml
contrib/gitian-descriptors/gitian-win.yml
contrib/scripts/pack.sh
doc/getting_started.md

-add gitian dir to .gitignore
-add libunistring and libevent_core to archive lib directory in pack.sh 
-clean up doc/getting_started.md to reflect proper linking libraries 
-add fix-mirror_base.patch to gitian-build.sh to fix gitian-builder's abnormal apt package size errors for ubuntu focal 
-add -lunistring to example gcc compilation instructions

gitian: bump build system to focal from bionic

---

include/dogecoin/utils.h
src/headersdb_file.c
src/net.c
src/spv.c
test/spv_tests.c

Addresses two key issues: 
1) Ensures proper spvnode exit on `dogecoin_node_group_shutdown`. 
2) Updates `dogecoin_btree_destroy` for complete header tree freeing, removes redundant loop from `dogecoin_headers_db_free`  and adds a stale header test in `spv_tests`.

net: added disconnected state for shutdown

---

.gitignore
CMakeLists.txt
Makefile.am
configure.ac
src/bench.c
src/intel/avx_t1/sha1_one_block_avx.asm
src/intel/avx_t1/sha256_one_block_avx.asm
src/intel/avx_t1/sha512_one_block_avx.asm
src/intel/include/clear_regs.inc
src/intel/include/os.inc
src/intel/sse_t1/sha1_one_block_sse.asm
src/intel/sse_t1/sha256_one_block_sse.asm
src/intel/sse_t1/sha512_one_block_sse.asm
src/sha2.c

- Updated SHA256/SHA512 algorithms using Intel AVX/SSE assembly.
- Updated CMake and Makefile for AVX/SSE, NASM and assembly support.
- Added benchmarks for SHA256 and Scrypt with assembly optimizations.
- Added AVX/SSE and benchmark configuration options.

src: added intel assembly for sha algs

---

Makefile.am

-this clears up an issue where when running make libsecp256k1.la was missing when libtool required it
-removes redundant clean-local command that was consistently ignored

build: require secp256k1 build first in Makefile

---

.github/workflows/ci.yml

As of today, macos-latest runs on an M1, therefore downgrade and pin version to lowest version available which is macos-12:
```
macOS 	3 	14 GB 	14 GB 	macos-12 or macos-11 	The macos-11 label has been deprecated and will no longer be available after 6/28/2024.
macOS 	4 	14 GB 	14 GB 	macos-13 	N/A
macOS 	3 (M1) 	7 GB 	14 GB 	macos-latest or macos-14 	The macos-latest label currently uses the macOS 14 runner image. 
```
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

ci: pin macos version to 12 instead of latest

---

configure.ac
include/dogecoin/net.h
include/dogecoin/spv.h
src/cli/spvnode.c
src/net.c
src/spv.c
src/wallet.c
test/spv_tests.c

Added HTTP server functionality to SPV node, enabling RESTful access to node and wallet data through endpoints like `/getBalance` and `/getChaintip`, along with a new command-line option `-u` for setting the server's IP and port.

net: added http server

---

include/dogecoin/portable_endian.h
include/dogecoin/scrypt.h
src/scrypt.c

it has endianness-related functions named the same

fix DragonFlyBSD 6.4-RELEASE support

---

include/dogecoin/address.h
src/address.c
test/address_tests.c

Addresses GH #217.
I proved the first test correct with a third-party derivation library; looking for feedback before I go further.

Make getDerivedHDAddress return address, not key

---

configure.ac

Added `-levent_core` to `AC_CHECK_LIB` for `event_extra` to fix NixOS builds. Since `libevent_extra` depends indirectly on `libevent_core`, we must explicitly link it because NixOS doesn't automatically resolve indirect dependencies like other distros.

config: add -levent_core to AC_CHECK_LIB for event_extra

---

.github/workflows/ci.yml

Added `tags` to `on:` in the CI to trigger actions on tag pushes, fixing the issue with sign actions not running. Also added verbose logging to macOS `codesign` steps and fixed an upload artifact name.

ci: added 'tags' to 'on:' for sign actions

---

.github/workflows/ci.yml

The macos-12 ci is deprecated, updated to macos-13.

ci: updated runner to macos-13

---

.github/workflows/ci.yml
depends/packages/packages.mk

Disabled `libunistring` for `mingw32` builds.  Windows provides its own unicode library that's currently used in `src\bip39.c`.

depends: disable libunistring for mingw32

---

doc/rest.md
src/rest.c

Updated `src/rest.c` to fix the `utxos` reference and improve error handling; removed `fclose` calls to prevent interference with `spvnode`. Added `doc/rest.md` to document the REST API endpoints.

src: updated reference and error handling in rest

---

doc/tools.md
src/cli/such.c

Updated `derive_child_keys` usage to note support for public child key derivation; added example in `tools.md`.

such: updated usage for public child keys

---

.github/workflows/ci.yml
CMakeLists.txt
configure.ac
src/sha2.c

Adds ARMv8 SHA-256 and ARMv8.2 SHA-512 crypto support using intrinsics; updates ci, cmake and config options.

sha2: added armv8 and armv8.2 crypto

---

doc/rest.md
src/rest.c

Added `getTimestamp` to REST API. Merge after https://github.com/dogecoinfoundation/libdogecoin/pull/229.

rest: added getTimestamp endpoint

---

doc/rest.md
include/dogecoin/spv.h
src/rest.c
src/spv.c

Added getLastBlockInfo to REST API. Merge after https://github.com/dogecoinfoundation/libdogecoin/pull/234.

rest: added getLastBlockInfo endpoint 

---

src/block.c
src/libevent/CMakeLists.txt
src/validation.c

Ports dogecoin/dogecoin@51cbc1f. Validates AuxPoW before other checks and ensures parent coinbase has an input. Merge after #229.

validation: check auxpow PoW before other checks

---

.github/workflows/ci.yml
doc/enclaves.md
src/optee/host/main.c
src/optee/ta/sub.mk

Updates op-tee build in the ci to enable RK3588's TRNG (`CFG_WITH_SOFTWARE_PRNG=n`), add `LIBDIR` overrides, fix a type cast warning, and update `enclave.md`. Also switches to `CFLAGS=-Wp,-D_FORTIFY_SOURCE=0` instead of `-U_FORTIFY_SOURCE` to disable checks not supported by OP-TEE since `-U_FORTIFY_SOURCE` compiler support varies.

optee: enable TRNG, add LIBDIR overrides, and switch fortify flag

---

src/sha2.c

Fixes compiler warnings for unused constant and functions when armv8 or armv82 crypto isn't enabled.

sha2: moved armv8 and armv82 guards

---

.github/workflows/ci.yml

Adds Windows native release and no TPM builds to CI, and switches from static to shared (DLL) builds. This implements #219.

ci: added windows native release and no tpm builds
